version: '3'

services:
  web:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./code:/code
      - ./site.conf:/etc/nginx/conf.d/default.conf
  php:
    container_name: php
    build:
      context: .
      dockerfile: PHP.Dockerfile
    volumes: 
      - ./code:/code

  mysql:
    container_name: better_database
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=base
      - MYSQL_USER=better
      - MYSQL_PASSWORD=base2
      - MYSQL_DATABASE=bettertherapy
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306